# Generated by Django 4.2.4 on 2023-09-06 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_instructor_alter_course_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students_courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_courses",
                to="courses.course",
            ),
        ),
    ]
